"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import sys
import os

if sys.platform == "darwin":
    from setuptools import setup
    import sysconfig
    import shutil
    import os
    import platform

    # Clean build directories if they exist
    if os.path.exists('build'):
        shutil.rmtree('build')
    if os.path.exists('dist'):
        shutil.rmtree('dist')

    APP = ['P2PP.py']
    DATA_FILES = ['p2pp.ui', 'p2ppconf.ui', "SendError.ui", "p3browser.ui"]
    OPTIONS = {
        'argv_emulation': True,
        "iconfile": "icons/icon.icns",
        "includes": [
            'PyQt5.QtWidgets',
            'PyQt5.QtGui', 
            'PyQt5.QtCore',
            'PyQt5.QtWebEngineWidgets',
            'PyQt5.QtWebEngine',
            'PyQt5.QtWebEngineCore'
        ],
        "excludes": [
            "tkinter",
            "matplotlib",
            "numpy",
            "_tkinter",
            "PIL"
        ],
        'packages': ['PyQt5'],
        'strip': False,
        'optimize': 0,
        'arch': 'universal2',
        'plist': {
            'CFBundleName': 'P2PP',
            'CFBundleDisplayName': 'P2PP',
            'CFBundleIdentifier': "com.p2pp.app",
            'CFBundleVersion': "1.0.0",
            'CFBundleShortVersionString': "1.0.0",
            'NSHighResolutionCapable': True,
            'LSMinimumSystemVersion': '11.0',
            'LSArchitecturePriority': ['arm64', 'x86_64']
        }
    }

    setup(
        app=APP,
        data_files=DATA_FILES,
        options={'py2app': OPTIONS},
        setup_requires=['py2app']
    )
    

if sys.platform == "linux":
    import sys
    import version
    from cx_Freeze import setup, Executable

    includefiles = ["p2pp.ui", 'p2ppconf.ui', "icons/icon.ico", "SendError.ui", "p3browser.ui"]
    excludes = ["tkinter"]
    includes = ['PyQt5.QtWidgets', 'PyQt5.QtGui', 'PyQt5.Qt', 'PyQt5', 'PyQt5.QtCore', 'PyQt5.QtWebEngineWidgets']

    build_exe_options = {"packages": ["os", "urllib3", "urllib3.contrib", "urllib3.contrib.appengine"], 'include_files': includefiles, "excludes": excludes, "includes": includes}

    setup(name="p2pp",
          version=version.Version,
          description="P2PP - Palette 2 Post Processing tool for Prusa Slicer",
          options={"build_exe": build_exe_options},
          executables=[Executable("P2PP.py", base=None, icon="icons/icon.ico")]
          )


if sys.platform == "win32":
    import sys
    import version
    from cx_Freeze import setup, Executable

    includefiles = ["p2pp.ui", 'p2ppconf.ui', "icons/icon.ico", "SendError.ui", "p3browser.ui"]
    excludes = ["tkinter"]
    includes = ['PyQt5.QtWidgets', 'PyQt5.QtGui', 'PyQt5.Qt', 'PyQt5', 'PyQt5.QtCore', 'PyQt5.QtWebEngineWidgets']

    build_exe_options = {"packages": ["os"], 'include_files': includefiles, "excludes": excludes, "includes": includes}

    # Updated MSI options with correct directory structure
    bdist_msi_options = {
        "upgrade_code": "{2E1D0F3B-768A-4E44-9D1C-85A4F8673C80}",
        "add_to_path": False,
        "initial_target_dir": r"[ProgramFilesFolder]\P2PP",
        "target_name": "P2PP",
        "directories": [
            ("SourceDir", "TARGETDIR", "SourceDir"),
            ("SourceDir/ProgramMenuFolder", "ProgramMenuFolder"),
            ("SourceDir/ProgramMenuFolder/P2PP", "ApplicationProgramsFolder"),
        ]
    }

    setup(name="p2pp",
          version=version.Version,
          description="P2PP - Palette 2 Post Processing tool for Prusa Slicer",
          options={
              "build_exe": build_exe_options,
              "bdist_msi": bdist_msi_options
          },
          executables=[Executable("p2pp.py", 
                                base="Win32GUI", 
                                icon="icons/icon.ico",
                                target_name="P2PP")]
          )