__author__ = 'Tom Van den Eede'
__copyright__ = 'Copyright 2018-2022, Palette2 Splicer Post Processing Project'
__credits__ = ['Tom Van den Eede',
               'Tim Brookman'
               ]
__license__ = 'GPLv3'
__maintainer__ = 'Tom Van den Eede'
__email__ = 'P2PP@pandora.be'
__status__ = 'BETA'

releaseinfo = {
    '4.16.0': "final release for PrusaSlicer 2.2.0",
    '5.0.0': "Development start for PrusaSlicer 2.3.0",
    '5.1.0': "Automatic detection of bed origin and size",
    '5.2.0': "Static side purge",
    '5.2.1': "Extruder clear added on static purge",
    '5.3.0': "error in minimal linear ping length error string",
    '5.4.0': "corrected is_movement_command checking",
    '5.5.0': "correction in non-synched support material handling",
    '5.6.0': "updated in Aboslute conversion post processing",
    '5.7.0': "Fixup More than 4 color print",
    "5.10.0": "General code restructuring for optimized processing",
    "5.10.1": "further process optimization",
    "5.10.2": "typo correction in TOOLSTART processing",
    "5.11.0": "memory usage optimization",
    "5.12.0": "further memory usage optimization, speed optimization",
    "5.13.0": "weekend development cut off with some bugfixes",
    "5.14.0": "rewrite path processing routines",
    "5.15.0": "taken care to retain empty comments",
    "5.16.0": "fixup Z-move after unload",
    "5.17.0": "fixup error when doing unprocessed tower entry",
    "5.18.0": "MAF file is generated as BINARY file",
    "5.19.0": "update to config parsin from prusa settings instead of parsing in full file",
    "5.20.0": "updated parseline routine to prevent repetitive function call",
    "5.21.0": "small correction in gui and filemant type processing",
    "5.22.0": "corrected tower delta",
    "5.23.0": "better tower detection",
    "5.24.0": "DO_NOT_GENERATE_M0 option added",
    "5.25.0": "possible incorrect tool select - corrected",
    "5.26.0": "remove M0 from existing output",
    "5.27.0": "correction in the tower delta calculation",
    "6.0.0":  "Switched to Qt gui + corrected variable layer",
    "6.0.1":  "Corrected info to enter to make sure it works in PS2.2",
    "6.0.2":  "OMEGA Error generation caused exception",
    "6.0.3":  "Updated internal logo / some minor corrections",
    "6.0.4":  "general changes to what is error vs information",
    "6.1.0":  "correction for asynchronous call ion MACOS + exist statements ",
    "6.1.1":  "resizable form",
    "6.1.2":  "windows version update - added ! in the outut path so it can be copied directly",
    "6.1.3":  "correction empty grid after tool purge should not be dropped (sidewipe)",
    "6.1.4":  "added positioning speed correction after removing the unload code",
    "6.1.5":  "swapped z-height correction nin unprocessed code with movement command to avoid collisions",
    "6.1.6":  "Introduction of configurator using -config flag",
    "6.1.7":  "ICorrection full purge first tool change",
    "6.1.8":  "configuraton - added basic material support",
    "6.2.0":  "configuraton - basic support for default configs",
    "6.2.1":  "Pressure Advance processing M527 added - tool number gets reset to 0",
    "6.2.2":  "Bug correction in the processing of the config parameters + added manual swap",
    "6.2.3":  "Initial tower optimizations",
    "6.2.4":  "Klipper toolchange support",
    "6.2.5":  "Fix for the tower delta implementation",
    "6.2.6":  "Fix for warning on TOWERDELTA",
    "6.2.7":  "Fix in full tower purge",
    "6.2.8":  "v.current_z value incorrrectly used in fullpurgetower reduction",
    "6.2.9":  "bed override",
    "6.2.10": "BB3D motor power command corrected",
    "6.2.11": "retraction after generating BRIM in fullpurge mode",
    "6.2.12": "changed code loading in UTF-8",
    "6.2.13": "IO Error for non-existing lastconf.conf file",
    "6.2.14": "Added extra check on empty printer profile on config",
    "6.2.15": "UTF8 config for config output",
    "6.2.16": "first layer height can be defined as % of layerheight",
    "6.2.17": "correction end processing with full purge",
    "6.2.18": "save_unprocessed processing corrected",
    "6.2.19": "FULLPURGEREDUCTION/WIPEFEEDRATE parameter correction in config support",
    "6.2.20": "SAVEUNPROCESED corrected - was not adding \\n  at the end of the lines",
    "6.2.21": "Allow spaces between keyywords = and values in  parameters",
    "6.2.22": "added extra config parameters",
    "6.2.23": "corrected processing for variable layer",
    "6.2.24": "applied wipe feed rate restriction to main tower as well",
    "6.2.25": "removed more than 4 color processing/ pplus correction",
    "6.2.26": "BB3D Minimal clearence height",
    "6.2.27": "Fix P+ loading offset and PPM procressing˚",
    "6.2.28": "fixed color names˚",
    "6.2.29": "bug fix absolute extrusion˚",
    "7.0.00": "Palette 3 intro",
    "7.0.01": "Fix output file error when no  output file is specified",
    "7.0.02": "Fix bug in side purge large unretract",
    "7.0.03": "Fix bug in side purge large unretract",
    "7.0.04": "Fix bug in palette+ when no default and actual algorithms are defines",
    "7.0.05": "Fix bug in palette+ invalid interpollation calculation",
    "7.0.06": "Added warning to place palette model specifier BEFORE algorithm info",
    "7.0.07": "Do not p2pp_process_file T0 if in Klipper mode",
    "7.0.08": "Handle TOOLCHANGE LOAD",
    "7.0.09": "Added BIGBRAIN3D_SINGLEBLOB",
    "7.1.00": "Fixup large retruact on blobs",
    "7.1.10": "Error in largeunretract routine",
    "7.1.11": "BUG Fix M220 processing",
    "7.1.12": "BUG Fix Added strip after PROFILE ID value, unretract speed set",
    "7.1.13": "Added SIDEWIPEZHOP parameter",
    "7.1.14": "Added SIDEWIPEZHOP_SKIPRETURN parameter",
    "7.2.00": "Fixup for Palette 3 Meta and Palette file changes",
    "7.2.01": "Fixup for drives array in Palette 3 json file",
    "7.2.02": "Preheat information parsing",
    "7.2.03": "Klipper - warning extruders / SuperSlicer - warning empty extrusion width",
    "7.2.04": "Updated Tower Detection for PS2.4",
    "7.2.05": "Updated TowerDelta Processing for PS2.4",
    "1.0.100": "PS2.4 release - Tower Delta first layer correction",
    "1.0.101": "PS2.4 release - No Sparse Layer Z-Drop correction",
    "1.0.102": "PS2.4 release - extra retract on blobs when going away from print",
    "1.0.110": "Incorrect check on definition of algorithms",
    "1.0.120": "updated generation of p3_thumbnail on PS24",
    "1.0.130": "Added P3_MINIMALTOTALFILAMENT parameter",
    "1.0.140": "BugFix with PS24 and fullpurgereduction",
    "1.0.150": "fixup palette.json file (algo definition bugfix)",
    "1.0.160": "fixup palette.json file (algo definition bugfix, part 2)",
    "1.0.170": "fixup meta.json - printing time calculation on short prints",
    "1.0.180": "bug fix - temperature waiting position",
    "1.0.190": "feature - issue warning when output file extension is not mcfx for palette 3",
    "1.0.200": "feature - updated minimal splice length for P3 ",
    "1.0.201": "buf fix - deleted output file",
    "1.0.202": "buf fix - deleted output file",
    "1.0.203": "32 char Printer Profiel IDs for P3",
    "1.0.204": "32 char Printer Profiel IDs for P3 // docs",
    "1.0.205": "added info on p3_thumbnail and link to Reference-COnfigs",
    "8.0.0": "PS2.4 Support - Cutoff point",
    "8.0.1": "Bug Fix - profile ID check",
    "8.0.2": "Bug Fix - no startup parm",
    "8.0.3": "Added upload functionality [hardcoded addresses - not yet supported by Palette 3]",
    "8.0.4": "Correction incorect extrusions while moving to tower.",
    "8.0.5": "Catch error for zero extrusionm width.",
    "8.0.6": "Prime BLOB error for BB3D correction.",
    "8.0.7": "P3 single color prints (with input select option).",
    "8.0.8": "F8640 parameter added to move back from tower.",
    "8.0.9": "Buf in single color prints.",
    "8.0.10": "LP reduced to minimum of 100mm.",
    "8.0.11": "BB3D primimng for PS2.4 - priming now BEFORE first extrusion.",
    "8.0.12": "Added FINISH_MOVES_M400.",
    "8.0.13": "Replace G4 S0 by M400 - also PS generated.",
    "8.0.14": "Correct location of .MAF / .MSF files.",
    "8.0.15": "Correct Z height after in PS2.4 in case of empty after purge.",
    "8.0.16": "Corrected project name for P2 output.",
    "8.0.17": "Corrected order of gcode inserted to avoid blob.",
    "8.0.18": "Correction for removal of empty grid in full purge where actual purge was needed.",
    "8.0.19": "Added web browser",
    "8.0.20": "Added initial BLOBSTER support[very BETA]/ Correction FULLPURGEREDUCTION",
    "8.0.21": "Added BLOBSTER_ADVANCED mode [very BETA]",
    "8.0.22": "Removed Z-Lift requirement",
    "8.0.23": "Corrected minimal print length check for P3 ",
    "8.0.24": "Added prime blobs for blobster",
    "8.0.25": "BUGFix P3/P3Pro accessory mode",
    "8.0.26": "Added parameter FIRMWARE_PURGE_LENGTH",
    "8.0.27": "Correction for accessory mode pings",
    "8.0.28": "Check for upload file size limits",
    "8.0.29": "BUGFix P3/P3Pro accessory mode",
    "8.0.30": "BUGFix Full Purge Mode",
    "8.0.31": "BUGFix Accessory Mode Pings in Empty Grids",
    "8.0.32": "BUGFix MAFX file",
    "8.0.33": "Support for webpreview of rotated screen on P3",
    "8.0.34": "Support for accessory file upload to P3, bugfix first purge line tower, retract on ping pauses",
    "8,0,35": "speedcheck in tower",
    "8,0,36": "catch error when decoding thumbnail",
    "8,0,37": "updates variable layer warning",
    "8,0,38": "autoaddsplice extended to support all modes !!! warning - if tower to close to objects, overlp my occur !!!",
    "8.0.39": "test rotate screen fix",
    "8.0.40": "fix extrusion in smart fan mode",
    "8.0.41": "autoadd is not compatible with blob counting",
    "8.0.42": "Z-HOP during the purge pauses",
    "8.0.43": "Speed in tower test",
    "8.0.44": "Correction M572 S float parameter on duet",
    "8.0.45": "Superslicer Z-correction",
    "8.0.46": "End of purge tower retract speed",
    "8.0.47": "layer config check altered",
    "8.0.48": "check for Tc and Tx command for MMU2 and filter them out",
    "8.0.49": "extra parameter to tune purging speed",
    "9.0.00": "Anomaly Z-correction on version PS 2.6.0",
    "9.0.01": "Anomaly Z-correction on version PS 2.6.0 - bugfix",
    "9.0.02": "Increased resolution of layer heights",
    "9.0.03": "Added FIRSTTOWERLAYERSPEEDUP to speed up first tower layer where possible",
    "9.0.04": "Allow spaces instead of underscores in the splice definition sequences",
    "9.0.05": "Automatic splcie increase - error message when in wrong mode",
    "9.1.00": "Reworked material / filament numbering on P3 output file to present range of consecutive numbers",
    "9.1.01": "Reworked material / filament numbering on P3 output file to present range of consecutive numbers",
    "9.1.02": "undo 9.1.1",
    "9.1.03": "added reverse splices and self-splices to the lgorithm list",
    "9.1.04": "more tweaking of thesplices and self-splices",
    "9.1.05": "issue with skipped layers in accessory mode",
    '--- RELEASE INFORMATION': 'END'
}

# general version info
MajorVersion = 9
MinorVersion = 1
Build = 5

Version = "{}.{:02}.{:02}".format(MajorVersion, MinorVersion, Build)

if __name__ == "__main__":
    print(Version)
