# PrusaSlicer config bundle — Palette 3 / Palette 3 Pro
# Import via PrusaSlicer: File > Import > Import Config Bundle

[printer:Palette 3 MM]
bed_shape = 0x0,200x0,200x200,0x200
origin = 0x0
num_extruders = 4
single_extruder_multi_material = 1
single_extruder_multi_material_priming = 0
single_extruder_multi_material_solid_infill = 0
single_extruder_multi_material_perimeters = 0
single_extruder_multi_material_infill = 0
wipe_tower = 1
wipe_tower_rotation_angle = 0
thumbnails = 640x480/PNG
end_gcode = ; EXTRA_CONFIG_VARIABLES
; wipe_tower_x = {wipe_tower_x}
; wipe_tower_y = {wipe_tower_y}
start_gcode = G28 ; home all axes
;P2PP PALETTE3_PRO
;P2PP P3_PROCESSPREHEAT
;P2PP P3_UPLOADFILE
;P2PP P3_SHOWPRINTERPAGE
;P2PP P3_HOSTNAME=<palette-ip>
;P2PP PRINTERPROFILE=<your-printer-profile-id>
;P2PP LINEARPINGLENGTH=350
;P2PP SPLICEOFFSET=80
;P2PP MINSTARTSPLICE=130
;P2PP MINSPLICE=90
;P2PP PURGETOPSPEED=70
;P2PP EXTRAENDFILAMENT=200
;P2PP PINGPONG_SPLICE=ENABLED
;P2PP MATERIAL_DEFAULT_0_0_0
;P2PP MATERIAL_PLA_PLA_2_1_2
;P2PP MATERIAL_PETG_PETG_2_1_4
;P2PP MATERIAL_PVA_PVA_2_6_11
;P2PP MATERIAL_ABS_ABS_4_0_0
;P2PP MATERIAL_TPU_TPU_2_6_10

[filament:PLA]
filament_type = PLA
[filament:PETG]
filament_type = PETG
[filament:PVA]
filament_type = PVA
[filament:ABS]
filament_type = ABS
[filament:TPU]
filament_type = TPU
