; generated by PrusaSlicer 2.6.0+win64
; estimated printing time (normal mode) = 4h 30m 15s
; filament_settings_id = "PLA;PLA"
; single_extruder_multi_material_priming = 0
; wipe_tower_no_sparse_layers = 0
; variable_layer_height = 0
; bed_shape = 0x0,250x0,250x210,0x210
; first_layer_temperature = 215,215
; first_layer_bed_temperature = 60
; max_print_height = 200
; wipe_tower_x = 230
; wipe_tower_y = 10
; min_skirt_length = 0
; skirts = 0
; wipe_tower_width = 20
; extrusion_width = 0.45
; layer_height = 0.2
; first_layer_height = 0.2
; support_material_synchronize_layers = 0
; support_material = 0
; nozzle_diameter = 0.4
; start_gcode = "G28 ; home all axes\nG1 Z0.280 F7200 ; move to first layer height\nM107 ; fan off\n;P2PP SPLICE_OFFSET=0\n;P2PP PURGE_FEEDRATE=5000\n;P2PP MIN_SPLICE_LENGTH=70\n;P2PP MIN_START_SPLICE_LENGTH=100\n;P2PP EXTRA_RUNOUT=150\n;P2PP MINIMAL_TOTAL_FILAMENT=0"
; extruder_colour = #FF0000;#0000FF
; filament_colour = #FF0000;#0000FF
; filament_diameter = 1.75,1.75
; filament_type = "PLA";"PLA"
; retract_length = 0.8,0.8
; gcode_flavor = reprap
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wiping_volumes_matrix = 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
; EXTRA_CONFIG_VARIABLES
; total filament used [mm] = 45000.0
; filament used [mm] = 22500.0,22500.0
; filament used [cm3] = 54.0,54.0
; TYPE:Custom
M107
M104 S215 T0 ; set extruder 0 temp
M104 S215 T1 ; set extruder 1 temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 T0 ; wait for extruder 0 temp
M109 S215 T1 ; wait for extruder 1 temp
G28 ; home all axes
G1 Z0.280 F7200 ; move to first layer height
M107 ; fan off
T0
;CP TOOLCHANGE_START
;TYPE:Skirt
;LAYERHEIGHT 0.2
G1 X10 Y10 F3600 E0.05
G1 X20 Y10 F1800 E0.5
G1 X20 Y20 E0.5
G1 X10 Y20 E0.5
G1 X10 Y10 E0.5
;CP TOOLCHANGE_END
;TYPE:Prime tower
;LAYERHEIGHT 0.2
;CP FIRST_LAYER_BRIM_START
G1 X230 Y10 F3600 E0.05
G1 X250 Y10 E0.5
G1 X250 Y30 E0.5
G1 X230 Y30 E0.5
G1 X230 Y10 E0.5
;CP FIRST_LAYER_BRIM_END
;TYPE:Perimeter
;LAYERHEIGHT 0.2
;CP NORMAL