#!/usr/bin/env bash
# Full end-to-end pipeline (issue #100):
#   PrusaSlicer (Flathub) -> p2pp -> G-code lint -> Palette 3 simulator
#
# Usage: scripts/e2e_pipeline.sh [model] [config]
# Env:   OUTDIR (default .live-test-out), SLICER (default prusa-slicer)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODEL="${1:-${REPO_ROOT}/tests/models/multi-color.stl}"
CONFIG="${2:-${REPO_ROOT}/profiles/prusaslicer/Palette3-cli.ini}"
OUTDIR="${OUTDIR:-${REPO_ROOT}/.live-test-out}"
SLICER="${SLICER:-prusa-slicer}"

command -v "${SLICER}" >/dev/null 2>&1 || {
  echo "FAIL: slicer '${SLICER}' not found; run scripts/install_prusaslicer.sh" >&2
  exit 1
}
[ -f "${MODEL}" ]  || { echo "FAIL: model not found: ${MODEL}" >&2;  exit 1; }
[ -f "${CONFIG}" ] || { echo "FAIL: config not found: ${CONFIG}" >&2; exit 1; }

rm -rf "${OUTDIR}"
mkdir -p "${OUTDIR}"
RAW="${OUTDIR}/raw.gcode"
PROCESSED="${OUTDIR}/processed.gcode"

# --- stage 1: slice ---------------------------------------------------------
echo "==> [1/4] Slicing $(basename "${MODEL}") with ${SLICER}"
# Flatpak PrusaSlicer needs a display even with QT_QPA_PLATFORM=offscreen —
# wrap in xvfb-run so it works headless in CI.
# The slicer may crash with Xlib errors after writing G-code (Flatpak sandbox
# cleanup), so don't use set -e for this command.
XVFB_WRAPPER=""
command -v xvfb-run >/dev/null 2>&1 && XVFB_WRAPPER="xvfb-run -a"
${XVFB_WRAPPER} "${SLICER}" --export-gcode --load "${CONFIG}" --output "${RAW}" "${MODEL}" || true
[ -s "${RAW}" ] || { echo "FAIL: slicer produced no G-code" >&2; exit 1; }

# p2pp/psconfig.py:160 keys off this string; without it p2pp will not recognise
# the file as PrusaSlicer output.
grep -q "generated by PrusaSlicer" "${RAW}" || {
  echo "FAIL: raw G-code is missing the PrusaSlicer banner" >&2; exit 1; }

# Guard against a config regression silently producing single-colour G-code —
# p2pp would then emit an empty splice table and the rest of the pipeline would
# "pass" while testing nothing.
TOOLCHANGES="$(grep -cE '^T[0-3][[:space:]]*$' "${RAW}" || true)"
echo "    tool changes in raw G-code: ${TOOLCHANGES}"
[ "${TOOLCHANGES}" -ge 2 ] || {
  echo "FAIL: expected multi-tool G-code, found ${TOOLCHANGES} tool changes" >&2
  exit 1; }

# --- stage 2: p2pp ----------------------------------------------------------
# NOTE: P2PP.py takes positional args (p2pp/main.py:100-104). There is no -i flag.
echo "==> [2/4] Post-processing with p2pp"
# p2pp imports GUI modules that use Xlib; wrap in xvfb-run in CI
XVFB2=""
command -v xvfb-run >/dev/null 2>&1 && XVFB2="xvfb-run -a"
QT_QPA_PLATFORM="${QT_QPA_PLATFORM:-offscreen}" \
  ${XVFB2} python3 "${REPO_ROOT}/P2PP.py" "${RAW}" "${PROCESSED}"
[ -s "${PROCESSED}" ] || { echo "FAIL: p2pp produced no output" >&2; exit 1; }

# --- stage 3: lint ----------------------------------------------------------
echo "==> [3/4] Linting p2pp output"
shopt -s nullglob
ARTIFACTS=("${PROCESSED}" "${OUTDIR}"/*.mcfx "${OUTDIR}"/*.msf)
python3 "${REPO_ROOT}/tests/lint_gcode.py" "${ARTIFACTS[@]}"

# --- stage 4: Palette 3 simulator ------------------------------------------
echo "==> [4/4] Palette 3 acceptance simulation"
python3 "${REPO_ROOT}/tests/p3_simulator.py" \
  --min-splice 70 --min-first-splice 100 --ping-length 350 \
  "${ARTIFACTS[@]}"

echo "==> E2E pipeline PASSED (artifacts in ${OUTDIR})"